const [teams, roster, rawMatches, rules, results] = await Promise.all(['teams','players','matches','rules','results'].map(name => fetch(`data/${name}.json`).then(r => r.json())));
const matches = rawMatches.map(([id,date,day,time,venue,gender,stage,group,team1,team2,umpire1,umpire2,scorer]) => ({id,date,day,time,venue,gender,stage,group,team1,team2,umpire1:umpire1||'To be assigned',umpire2:umpire2||'To be assigned',scorer:scorer||'To be assigned',status:'Scheduled',team1Score:null,team2Score:null,winner:null,resultText:null,...results[id]}));
const startTime = match => {const timestamp=Date.parse(`${match.date}, 2026 ${match.time.split(' - ')[0]}`);return Number.isNaN(timestamp)?Number.POSITIVE_INFINITY:timestamp;};
matches.sort((a,b) => startTime(a) - startTime(b));
const playerMap = Object.fromEntries(roster.map(row => [row.team,row.players]));
const app = document.querySelector('#app');
const officialNames = official => Array.isArray(official)?official:[official];
const formatOfficial = official => officialNames(official).join(', ');
const officialsSummary = () => {const assignments=new Map();matches.filter(match=>match.status!=='Cancelled').forEach(match=>[['Umpire 1',match.umpire1],['Umpire 2',match.umpire2],['Scorer',match.scorer]].forEach(([role,official])=>officialNames(official).forEach(name=>{if(name==='To be assigned')return;if(!assignments.has(name))assignments.set(name,[]);assignments.get(name).push({role,match});})));return [...assignments.entries()].map(([name,duties])=>`<article class="official-schedule"><h3>${name}</h3><ol>${duties.map(({role,match})=>`<li><b>${match.id} · ${role}</b><span>${match.day}, ${match.date} · ${match.time} · ${match.venue}</span><span>${match.team1} vs ${match.team2}</span></li>`).join('')}</ol></article>`).join('');};
const ruleContent = items => { let html='<ul>'; let activeSection=''; items.forEach(item=>{const label=/^\((Men|Women)\)\s*/i.exec(item.trim()); const section=label?.[1]||''; if(section&&section!==activeSection){html+=`</ul><h4 class="rule-subsection">${section}</h4><ul>`;activeSection=section;} html+=`<li>${label?item.trim().slice(label[0].length):item}</li>`;}); return `${html}</ul>`; };
const leagueSummary = (title, teamList) => `<section class="league-group"><h3>${title}</h3>${teamList.map(team=>{const fixtures=matches.filter(match=>match.stage==='League'&&match.status!=='Cancelled'&&(match.team1===team.name||match.team2===team.name));return `<article class="team-schedule"><h4>${team.name}</h4><ol>${fixtures.map(match=>`<li><b>${match.day}, ${match.date}</b> — ${match.time}<span>${match.id} · vs ${match.team1===team.name?match.team2:match.team1} · ${match.venue}</span></li>`).join('')}</ol></article>`;}).join('')}</section>`;
const card = m => `<article class="match-card"><div class="match-card-top"><span>${m.id} · ${m.gender} · ${m.stage}${m.group !== 'N/A' ? ` · Group ${m.group}` : ''}</span><span class="pill">${m.status}</span></div><div class="teams-line"><b>${m.team1}</b><span>VS</span><b>${m.team2}</b></div><div class="scoreline"><p><b>${m.team1}</b><span>${m.team1Score || 'Score pending'}</span></p><p><b>${m.team2}</b><span>${m.team2Score || 'Score pending'}</span></p></div><p class="result-line">${m.status === 'Abandoned' ? (m.resultText || 'Match abandoned') : (m.winner ? `<b>Winner: ${m.winner}</b>${m.resultText ? ` · ${m.resultText}` : ''}` : (m.resultText || 'Result pending'))}</p><div class="match-meta"><strong>${m.day}, ${m.date}</strong><span>${m.time}</span><span>${m.venue}</span></div><div class="officials"><span>OFFICIALS</span><p><b>Umpire 1</b>${formatOfficial(m.umpire1)}</p><p><b>Umpire 2</b>${formatOfficial(m.umpire2)}</p><p><b>Scorer</b>${formatOfficial(m.scorer)}</p></div></article>`;
function standings(groupTeams){const rows=Object.fromEntries(groupTeams.map(t=>[t.name,{name:t.name,p:0,w:0,l:0,pts:0,runsFor:0,oversFaced:0,runsAgainst:0,oversBowled:0}]));matches.filter(m=>m.stage==='League'&&(m.status==='Completed'||m.status==='Forfeited')&&rows[m.team1]&&rows[m.team2]).forEach(m=>{const first=rows[m.team1],second=rows[m.team2];first.p++;second.p++;if(m.winner===m.team1){first.w++;first.pts+=2;second.l++;}else if(m.winner===m.team2){second.w++;second.pts+=2;first.l++;}else{first.pts++;second.pts++;}if(Number.isFinite(m.team1Runs)&&Number.isFinite(m.team1NrrOvers)&&Number.isFinite(m.team2Runs)&&Number.isFinite(m.team2NrrOvers)){first.runsFor+=m.team1Runs;first.oversFaced+=m.team1NrrOvers;first.runsAgainst+=m.team2Runs;first.oversBowled+=m.team2NrrOvers;second.runsFor+=m.team2Runs;second.oversFaced+=m.team2NrrOvers;second.runsAgainst+=m.team1Runs;second.oversBowled+=m.team1NrrOvers;}});return Object.values(rows).map(row=>({...row,nrr:row.oversFaced?((row.runsFor/row.oversFaced)-(row.runsAgainst/row.oversBowled)).toFixed(3):'—'})).sort((a,b)=>b.pts-a.pts||(Number(b.nrr)||0)-(Number(a.nrr)||0)||a.name.localeCompare(b.name));}
function table(title, list){return `<section class="standings-card"><h3>${title}</h3><table><thead><tr><th>Team</th><th>P</th><th>W</th><th>L</th><th>Pts</th><th>NRR</th></tr></thead><tbody>${standings(list).map(t=>`<tr><td>${t.name}</td><td>${t.p}</td><td>${t.w}</td><td>${t.l}</td><td>${t.pts}</td><td>${t.nrr}</td></tr>`).join('')}</tbody></table></section>`;}
function render(){const upcomingMatches=matches.filter(match=>match.status==='Scheduled');app.innerHTML=`
<section id="home" class="hero"><p class="eyebrow">BLOSSOM HILLS WILLOW RIDGE GANESHOTAV</p><h1>BLOSSOM HILLS WILLOW RIDGE<br>CRICKET TOURNAMENT <span>2026</span></h1><p>Fixtures, teams, points, and tournament rules.</p></section>
<section class="section"><h2 class="section-title">Upcoming matches</h2><p class="section-intro">League fixtures and knockout rounds.</p><div class="cards two">${upcomingMatches.slice(0,4).map(card).join('')}</div></section>
<section id="matches" class="section"><h2 class="section-title">Matches</h2><div class="filters" id="match-filters"><button class="filter active" data-filter="All">All</button><button class="filter" data-filter="Men">Men</button><button class="filter" data-filter="Women">Women</button><button class="filter" data-filter="Knockout">Knockout</button></div><div class="cards" id="match-list"></div></section>
<section id="standings" class="section"><h2 class="section-title">Points table</h2><p class="section-intro">Standings update automatically after completed results are entered.</p>${table('MEN · GROUP A',teams.filter(t=>t.gender==='Men'&&t.group==='A'))}${table('MEN · GROUP B',teams.filter(t=>t.gender==='Men'&&t.group==='B'))}${table('WOMEN',teams.filter(t=>t.gender==='Women'))}</section>
<section id="teams" class="section"><h2 class="section-title">Teams</h2><p class="section-intro">Player lists are partial and will grow during the tournament.</p><div class="team-tabs"><button class="active" data-teamtab="Men">MEN</button><button data-teamtab="Women">WOMEN</button></div><div class="cards three" id="team-list"></div></section>
<section id="rules" class="section"><h2 class="section-title">Tournament rules</h2><p class="section-intro">Official 2026 rules, organized for quick reference.</p><p class="notice">The committee may clarify or amend rules where necessary. Umpire and committee decisions are final.</p><div id="rule-list">${rules.map(r=>`<details class="rule-card"><summary>${r.title}</summary><div>${ruleContent(r.items)}</div></details>`).join('')}</div></section>`;
const list=document.querySelector('#match-list');const showMatches=filter=>{const activeMatches=matches.filter(m=>m.status!=='Cancelled');const selected=filter==='All'?activeMatches:filter==='Knockout'?activeMatches.filter(m=>m.stage!=='League'):activeMatches.filter(m=>m.gender===filter);list.innerHTML=selected.map(card).join('');};showMatches('All');
document.querySelector('#match-filters').addEventListener('click',e=>{if(!e.target.dataset.filter)return;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===e.target));showMatches(e.target.dataset.filter);});
const showTeams=gender=>{document.querySelector('#team-list').innerHTML=teams.filter(t=>t.gender===gender).map(t=>{const names=playerMap[t.name]||[];return `<article class="team-card"><h3>${t.name}</h3><p>${gender==='Men'?`Group ${t.group}`:'Women’s League'} · Captain: ${t.captain||'Not known'}</p><button data-roster="${t.id}">View ${names.length} listed player${names.length===1?'':'s'}</button><div class="roster" id="${t.id}">${names.length?`<ol>${names.map(n=>`<li>${n}</li>`).join('')}</ol>`:'No players listed yet.'}</div></article>`}).join('');document.querySelectorAll('[data-roster]').forEach(b=>b.addEventListener('click',()=>document.querySelector(`#${b.dataset.roster}`).classList.toggle('open')));};showTeams('Men');document.querySelector('.team-tabs').addEventListener('click',e=>{if(!e.target.dataset.teamtab)return;document.querySelectorAll('.team-tabs button').forEach(x=>x.classList.toggle('active',x===e.target));showTeams(e.target.dataset.teamtab);});}
render();
document.querySelector('#matches').insertAdjacentHTML('afterend', `<section id="officials-summary" class="section"><h2 class="section-title">Umpiring & Scoring Summary</h2><p class="section-intro">Match assignments grouped by individual.</p><div class="officials-summary-list">${officialsSummary()}</div></section>`);
document.querySelector('#matches').insertAdjacentHTML('afterend', `<section id="league-summary" class="section"><h2 class="section-title">League match summary</h2><p class="section-intro">Each team’s four men’s or two women’s league fixtures.</p>${leagueSummary('MEN · GROUP A',teams.filter(t=>t.gender==='Men'&&t.group==='A'))}${leagueSummary('MEN · GROUP B',teams.filter(t=>t.gender==='Men'&&t.group==='B'))}${leagueSummary('WOMEN',teams.filter(t=>t.gender==='Women'))}</section>`);
