const [teams, roster, rawMatches, rules, results] = await Promise.all(['teams','players','matches','rules','results'].map(name => fetch(`data/${name}.json`).then(r => r.json())));
const matches = rawMatches.map(([id,date,day,time,venue,gender,stage,group,team1,team2,umpire1,umpire2,scorer]) => ({id,date,day,time,venue,gender,stage,group,team1,team2,umpire1:umpire1||'To be assigned',umpire2:umpire2||'To be assigned',scorer:scorer||'To be assigned',status:'Scheduled',team1Score:null,team2Score:null,winner:null,resultText:null,...results[id]}));
const playerMap = Object.fromEntries(roster.map(row => [row.team,row.players]));
const app = document.querySelector('#app');
const card = m => `<article class="match-card"><div class="match-card-top"><span>${m.id} · ${m.gender} · ${m.stage}${m.group !== 'N/A' ? ` · Group ${m.group}` : ''}</span><span class="pill">${m.status}</span></div><div class="teams-line"><b>${m.team1}</b><span>VS</span><b>${m.team2}</b></div><div class="scoreline"><p><b>${m.team1}</b><span>${m.team1Score || 'Score pending'}</span></p><p><b>${m.team2}</b><span>${m.team2Score || 'Score pending'}</span></p></div><p class="result-line">${m.status === 'Abandoned' ? (m.resultText || 'Match abandoned') : (m.winner ? `<b>Winner: ${m.winner}</b>${m.resultText ? ` · ${m.resultText}` : ''}` : (m.resultText || 'Result pending'))}</p><div class="match-meta"><strong>${m.day}, ${m.date}</strong><span>${m.time}</span><span>${m.venue}</span></div><div class="officials"><span>OFFICIALS</span><p><b>Umpire 1</b>${m.umpire1}</p><p><b>Umpire 2</b>${m.umpire2}</p><p><b>Scorer</b>${m.scorer}</p></div></article>`;
function standings(groupTeams){return groupTeams.map(t=>({name:t.name,p:0,w:0,l:0,pts:0,nrr:'—'})).sort((a,b)=>b.pts-a.pts||a.name.localeCompare(b.name));}
function table(title, list){return `<section class="standings-card"><h3>${title}</h3><table><thead><tr><th>Team</th><th>P</th><th>W</th><th>L</th><th>Pts</th><th>NRR</th></tr></thead><tbody>${standings(list).map(t=>`<tr><td>${t.name}</td><td>${t.p}</td><td>${t.w}</td><td>${t.l}</td><td>${t.pts}</td><td>${t.nrr}</td></tr>`).join('')}</tbody></table></section>`;}
function render(){const next=matches[0];app.innerHTML=`
<section id="home" class="hero"><p class="eyebrow">BLOSSOM HILLS WILLOW RIDGE GANESHOTAV</p><h1>BLOSSOM HILLS WILLOW RIDGE<br>CRICKET TOURNAMENT <span>2026</span></h1><p>Fixtures, teams, points, and tournament rules.</p><article class="next-match"><span class="label">NEXT MATCH</span><div class="match-teams"><b>${next.team1}</b><span>VS</span><b>${next.team2}</b></div><div class="match-meta"><strong>${next.day}, ${next.date}</strong><span>${next.time}</span><span>${next.venue}</span></div></article></section>
<section class="section"><h2 class="section-title">Upcoming matches</h2><p class="section-intro">League fixtures and knockout rounds.</p><div class="cards two">${matches.slice(0,4).map(card).join('')}</div></section>
<section id="matches" class="section"><h2 class="section-title">Matches</h2><div class="filters" id="match-filters"><button class="filter active" data-filter="All">All</button><button class="filter" data-filter="Men">Men</button><button class="filter" data-filter="Women">Women</button><button class="filter" data-filter="Knockout">Knockout</button></div><div class="cards" id="match-list"></div></section>
<section id="standings" class="section"><h2 class="section-title">Points table</h2><p class="section-intro">Standings update automatically after completed results are entered.</p>${table('MEN · GROUP A',teams.filter(t=>t.gender==='Men'&&t.group==='A'))}${table('MEN · GROUP B',teams.filter(t=>t.gender==='Men'&&t.group==='B'))}${table('WOMEN',teams.filter(t=>t.gender==='Women'))}</section>
<section id="teams" class="section"><h2 class="section-title">Teams</h2><p class="section-intro">Player lists are partial and will grow during the tournament.</p><div class="team-tabs"><button class="active" data-teamtab="Men">MEN</button><button data-teamtab="Women">WOMEN</button></div><div class="cards three" id="team-list"></div></section>
<section id="rules" class="section"><h2 class="section-title">Tournament rules</h2><p class="section-intro">Official 2026 rules, organized for quick reference.</p><p class="notice">The committee may clarify or amend rules where necessary. Umpire and committee decisions are final.</p><div id="rule-list">${rules.map(r=>`<details class="rule-card"><summary>${r.title}</summary><div><ul>${r.items.map(i=>`<li>${i}</li>`).join('')}</ul></div></details>`).join('')}</div></section>`;
const list=document.querySelector('#match-list');const showMatches=filter=>{const selected=filter==='All'?matches:filter==='Knockout'?matches.filter(m=>m.stage!=='League'):matches.filter(m=>m.gender===filter);list.innerHTML=selected.map(card).join('');};showMatches('All');
document.querySelector('#match-filters').addEventListener('click',e=>{if(!e.target.dataset.filter)return;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===e.target));showMatches(e.target.dataset.filter);});
const showTeams=gender=>{document.querySelector('#team-list').innerHTML=teams.filter(t=>t.gender===gender).map(t=>{const names=playerMap[t.name]||[];return `<article class="team-card"><h3>${t.name}</h3><p>${gender==='Men'?`Group ${t.group}`:'Women’s League'} · Captain: ${t.captain||'Not known'}</p><button data-roster="${t.id}">View ${names.length} listed player${names.length===1?'':'s'}</button><div class="roster" id="${t.id}">${names.length?`<ol>${names.map(n=>`<li>${n}</li>`).join('')}</ol>`:'No players listed yet.'}</div></article>`}).join('');document.querySelectorAll('[data-roster]').forEach(b=>b.addEventListener('click',()=>document.querySelector(`#${b.dataset.roster}`).classList.toggle('open')));};showTeams('Men');document.querySelector('.team-tabs').addEventListener('click',e=>{if(!e.target.dataset.teamtab)return;document.querySelectorAll('.team-tabs button').forEach(x=>x.classList.toggle('active',x===e.target));showTeams(e.target.dataset.teamtab);});}
render();
